sudo: false
language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - /^Release.*$/
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test-travis;
after_success:
  - npm install coveralls@2.10.0 && cat ./coverage/lcov/lcov.info | coveralls
